### ISSUE TITLE
Inquiry about of `xmask`

### ISSUE THREAD

**Issue by kongdd** [KMarkert/LohmannRouting.jl#1]
In <https://github.com/KMarkert/LohmannRouting.jl/blob/main/src/routing.jl#L19>, 
```julia
xmask[i,j] = sqrt( +((sides[i,j].^2)...)) / 2
```
why divide 2?
Could you give some explanation?

**Comment by KMarkert** [comment]
The division by 2 was an misunderstanding by me on how xmask is calculated. I thought it was the hypothetical longest path length from the center grid cell. xmask is actually the flow path through the cell (one edge to the other). This is admittedly not the correct way to calculate the xmask value. It should be based off of flow direction and the cell size.
If is is a diagonal flow then the flow length should be `sqrt(x^2 + y^2)` and if the flow is in the x direction then just the x resolution (same logic for y direction).

So, this needs to be updated based on that...

**Comment by kongdd** [comment]
Thanks for your detailed explanation. That make sense.
